### ISSUE TITLE
How to dynamically make a cell read only using jstree-table plugin

### ISSUE THREAD

**Issue by sandipg76** [adamjimenez/jstree-table#15]
I want to make some columns which I have added using the table plugin to jstree, dynamically read only, so that editing should be disabled on those cells. I have set the contextmenu plugin to true. Now when I right click on the column, an edit pop-up shows up and then allows me to edit the field. I want this to be conditional logic so that some fields are editable and some are read only.
Any help would really be appreciated?

**Comment by adamjimenez** [comment]
we could a config option to pass in either a click handler or a menu object...
