### ISSUE TITLE
Per Row Buttons

### ISSUE THREAD

**Issue by bryanllewis** [adamjimenez/jstree-table#20]
While clicking an item in the tree opens that item (if not a leaf), I also need to allow for a column on the right side of table that would allow me to have action buttons for any row/level in the tree.  Is this possible?  Essentially I need a "Add" buttons (icons) for non-leaves and "Edit"/"Delete" buttons for leaves.

**Comment by adamjimenez** [comment]
You can use the column "format" function to output buttons. Then use jquery to hook them up.
See the demo to see how the format function works.
