### ISSUE TITLE
first column stops printing data

### ISSUE THREAD

**Issue by maliv21** [adamjimenez/jstree-table#22]
very good job! i have an issue when i use mydata first column stops print data. other columns are printing ok. i am sure i get data to print..

**Comment by adamjimenez** [comment]
Thanks, can you put a jsfiddle together?

**Comment by maliv21** [comment]
i ll do it..thnx for qiock reply

**Comment by maliv21** [comment]
i attach a photo to see what happens..thanx
![example](https://user-images.githubusercontent.com/34087908/33377538-7adfa126-d51a-11e7-8e92-e387db8cbdc7.png)

**Comment by adamjimenez** [comment]
I need a fiddle to dig into this.
