### ISSUE TITLE
"themes" : { "stripes" : true } works  not properly?

### ISSUE THREAD

**Issue by Jiangshan00001** [adamjimenez/jstree-table#25]
![image](https://user-images.githubusercontent.com/13453002/36844092-3dc2ddde-1d8c-11e8-9133-e8329f50abce.png)

if i use "core"{ "themes" : { "stripes" : true }...}   in jstree, every row has different gray color. but the columns has no such effect except the first one column.

**Comment by adamjimenez** [comment]
can you create a jsfiddle for this?

**Comment by vinithdilip** [comment]
![Screenshot from 2023-08-11 12-35-36](https://github.com/adamjimenez/jstree-table/assets/3378500/ae657510-e273-47a8-8686-c44f3c4f21ff)


Facing the same, please guide us further
