### ISSUE TITLE
Can someone please tell me what is wrong with my code?

### ISSUE THREAD

**Issue by vicn1222** [adamjimenez/jstree-table#40]
I can show the entire tree table. If I remove "tab-pane" from "menu2", the table show all data, but it breaks other parts of my code. Also, if I resize the column, the data are shown. What is wrong in my code below?

Thank you!

<!DOCTYPE html>
<html>
  <head>

    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>JSTREE TABLE</title>

    <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js'></script>
    <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/bootstrap-table/dist/bootstrap-table.min.js"></script>
    <script src='https://static.jstree.com/latest/assets/dist/jstree.min.js'></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/jstreetable@latest/jstreetable.min.js"></script>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/x-editable/1.5.0/bootstrap3-editable/css/bootstrap-editable.css" />
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@latest/dist/bootstrap-table.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.4.1/css/bootstrap-datepicker3.min.css"/>
    <link rel="stylesheet" href="https://unpkg.com/bootstrap-table@latest/dist/extensions/filter-control/bootstrap-table-filter-control.min.css"/>
    <link rel='stylesheet' href='https://static.jstree.com/latest/assets/dist/themes/default/style.min.css'>
    <link rel='stylesheet' href='https://code.jquery.com/ui/1.12.0/themes/smoothness/jquery-ui.min.css'>

  </head>
  <body class='container-fluid'>

<ul class="nav nav-tabs">
  <li class="active"><a data-toggle="tab" href="#menu0"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Config</a></li>
  <li><a data-toggle="tab" href="#menu1"><span class="glyphicon glyphicon-user" aria-hidden="true"></span>Add User</a></li>
  <li><a data-toggle="tab" href="#menu2"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span>Get Tree</a></li>
</ul>
<div class="tab-content" style="margin-top: 10px;">

  <div id="menu0" class="col-md-4 tab-pane fade in active">
  </div>

  <div id="menu1" class="tab-pane fade">
  </div>

  <div id="menu2" class="tab-pane fade">
    <div class="tree_area_div">
      <div id="jstree"> </div>
    </div>
  </div>

</div>
<script type='text/javascript' src='https://code.jquery.com/ui/1.12.0/jquery-ui.min.js'></script>
<script src='https://cdnjs.cloudflare.com/ajax/libs/jquery.payment/1.0.1/jquery.payment.min.js'></script>

<script>

$(document).ready(function(){
   $('.nav.nav-tabs a').click(function(e) {
     e.preventDefault();
     $(this).tab('show');
   });
   $("ul.nav-tabs > li > a").on("shown.bs.tab", function(e) {
     var id = $(e.target).attr("href").substr(1);
     window.location.hash = id;
   });
   $('.nav.nav-tabs a[href="' + window.location.hash + '"]').tab('show');
});
  
</script>

    <script type="text/javascript">//<![CDATA[

// tree data
var data;
data = [{
  text: "Products",
  data: {},
  children: [{
    text: "Fruit",
    data: {},
    children:[
      {text: "Apple", data: {price: 0.1, quantity: 20}},
      {text: "Banana", data: {price: 0.2, quantity: 31}},
      {text: "Grapes", data: {price: 1.99, quantity: 34}},
      {text: "Mango", data: {price: 0.5, quantity: 8}},
      {text: "Melon", data: {price: 0.8, quantity: 4}},
      {text: "Pear", data: {price: 0.1, quantity: 30}},
      {text: "Strawberry", data: {price: 0.15, quantity: 32}}
    ],
    'state': {'opened': true}
  }, {
    text: "Vegetables",
    data: {},
    children:[
      {text: "Aubergine", data: {price: 0.5, quantity: 8}},
      {text: "Broccoli", data: {price: 0.4, quantity: 22}},
      {text: "Carrot", data: {price: 0.1, quantity: 32}},
      {text: "Cauliflower", data: {price: 0.45, quantity: 18}},
      {text: "Potato", data: {price: 0.2, quantity: 38}}
    ]
  }],
  'state': {'opened': true}
}];

// load jstree
$("div#jstree").jstree({
  plugins: ["table","dnd","contextmenu","sort"],
  core: {
    data: data
  },
  // configure tree table
  table: {
    columns: [
      {width: 200, header: "Name"},
      {width: 150, value: "price", header: "Price", format: function(v) {if (v){ return '$'+v.toFixed(2) }}},
      {width: 150, value: "quantity", header: "Qty"}
    ],
    resizable: true,
    draggable: true,
    contextmenu: true,
    width: 500,
    height: 800
  }
});

  //]]></script>

  </body>
</html>

**Comment by vicn1222** [comment]
Hmmm, can't paste html code in here?

**Comment by adamjimenez** [comment]
best to setup a jsfiddle

**Comment by vicn1222** [comment]
> best to setup a jsfiddle

Thanks. I have set it up in jsfiddle, below is the link. Please click "Get Tree", only first column data are shown. When I resize the column, the rest columns show up. If I remove "tab-pane" from the tree tab, all columns show up. But if I remove "tab-pane", other codes break....Thank you.

https://jsfiddle.net/vicn1222/7d9j2c8g/

**Comment by adamjimenez** [comment]
The problem is that the tree is loaded before the tab is displayed and therefore the cell calculations are wrong.
This can be solved by loading the tree when the tab is shown. https://jsfiddle.net/1n86cbs5/

e.g.
```
    $('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
        // load tree
    });
```

See fiddle:
https://jsfiddle.net/1n86cbs5/

I will tweak the default cell height so that it's never 0.

**Comment by vicn1222** [comment]
Excellent. It works flawlessly! Thank you!
